spring.application.name=user-service
server.port=${SERVER_PORT:8082}

spring.datasource.url=jdbc:h2:file:./data/users_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=dbvalle
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update

api.security.token.secret=${JWT_SECRET:my-secret-key-that-should-be-very-long}

# URL del auth-service para validar tokens entrantes
auth.service.url=${AUTH_SERVICE_URL:http://localhost:8081}
